# configure sysctl setttings
- name: configure sysctl tunables
  ansible.builtin.template:
    src: local.conf.j2
    dest: /etc/sysctl.d/local.conf
  register: sysctl_conf

- name: restart sysctl
  ansible.builtin.service:
    name: sysctl
    state: restarted
  when: sysctl_conf.changed


# enable lldpd
- name: enable starting lldpd on boot
  service:
    name: lldpd
    enabled: yes
    state: started


# prepare network config
- name: create config directory
  ansible.builtin.file:
    path: /etc/ifstate
    state: directory

- name: enable ifstate on boot
  ansible.builtin.service:
    name: ifstate
    enabled: yes


# prepare firewall (we have no ruleset, yet)
- name: Disable nftables on boot
  ansible.builtin.service:
    name: nftables
    enabled: false


# configure bird env
- name: create ddix-deploy user
  ansible.builtin.user:
    name: ddix-deploy
    password: "*"
    groups: bird

- name: configure authorized_keys
  ansible.builtin.authorized_key:
    user: ddix-deploy
    key: "{{ (ssh_authorized_keys, arouteserver_public_key)|join(\"\n\") }}"
    exclusive: yes

- name: configure doas for ddix-deploy
  ansible.builtin.template:
    src: ddix-deploy.conf.j2
    dest: /etc/doas.d/ddix-deploy.conf

- name: create config directory
  ansible.builtin.file:
    path: /etc/bird
    state: directory
    owner: ddix-deploy
    group: bird
    mode: 0750

- name: configure bird's rc config
  ansible.builtin.template:
    src: bird.j2
    dest: /etc/conf.d/bird

- name: enable starting bird on boot
  ansible.builtin.service:
    name: bird
    enabled: yes
