#!/usr/bin/env ansible-playbook

- name: Setup system
  hosts: rs
  roles:
    - base
    - network
    - checkmk
  tags:
    - base

- name: Setup bird
  hosts: rs
  roles:
    - rs
    - exporters
    - status
  tags:
    - rs

- name: Write audit log
  hosts: rs
  roles:
    - auditlog
  tags:
    - base
    - rs
