#!/usr/bin/env ansible-playbook

- name: setup system
  hosts: rs
  roles:
    - base
    - network
  tags:
    - base

- name: setup bird
  hosts: rs
  roles:
    - rs
    - exporters
  tags:
    - rs

- name: write audit log
  hosts: rs
  roles:
    - auditlog
  tags:
    - base
    - rs
